routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/index', function () {
    return view('index');
});

Route::get('/', function () {
    return view('accueil');
});

Route::get('/services', function () {
    return view('services');
});

Route::get('/habitats', function () {
    return view('habitats');
});

Route::get('/avis', function () {
    return view('avis');
});

Route::get('/contact', function () {
    return view('contact');
});

Route::get('/connexion', [App\Http\Controllers\ConnexionController::class, 'formulaire']);
Route::post('/connexion', [App\Http\Controllers\ConnexionController::class, 'traitement']);


Route::get('/savane', function () {
    return view('savane');
});

Route::get('/jungle', function () {
    return view('jungle');
});

Route::get('/marais', function () {
    return view('marais');
});

Route::get('/mon-compte', [App\Http\Controllers\CompteController::class, 'accueil']);

Route::get('/deconnexion', [App\Http\Controllers\CompteController::class, 'deconnexion']);

Route::post('/logout', function () {
    auth()->logout();
    return redirect('/');
})->name('logout');


Route::middleware(['isAdmin'])->group(function () {
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal']);
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal'])->name('admin.dashboard');

    Route::get('gestionDesServices', [\App\Http\Controllers\ServiceController::class, 'indexGestionService'])->name('gestionDesServices');
    Route::resource('gestionDesServices', \App\Http\Controllers\ServiceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesHabitats', [\App\Http\Controllers\HabitatController::class, 'indexGestionHabitat'])->name('gestionDesHabitats');
    Route::resource('gestionDesHabitats', \App\Http\Controllers\HabitatController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesAnimaux', [\App\Http\Controllers\AnimalController::class, 'indexGestionAnimal'])->name('gestionDesAnimaux');
    Route::resource('gestionDesAnimaux', \App\Http\Controllers\AnimalController::class)->only(['destroy', 'show', 'edit', 'update', 'create', 'store']);

    Route::get('gestionDesRaces', [\App\Http\Controllers\RaceController::class, 'indexGestionRace'])->name('gestionDesRaces');
    Route::resource('gestionDesRaces', \App\Http\Controllers\RaceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('ajout-Compte', [\App\Http\Controllers\UserController::class, 'index'])->name('ajoutCompte');
    Route::resource('ajout-Compte', \App\Http\Controllers\UserController::class)->only(['store']);

    Route::get('/indexHoraires', function () {
        return view('indexHoraires');
    });

    Route::get('/indexComptesRendus', [App\Http\Controllers\VeterinaryReportController::class, 'adminIndex'])->name('admin.veterinaryReports.index');
});

use App\Http\Controllers\AnimalController;
use App\Http\Controllers\EmployeeNourritureController;
use App\Http\Controllers\VeterinaryReportController;
Route::get('/animal/{id}', [AnimalController::class, 'showAnimalDetails'])->name('animal.details');
Route::post('/animal/{id}/increment-view', [AnimalController::class, 'incrementView'])->name('animal.incrementView');

Route::get('/jungle', [AnimalController::class, 'jungle']);
Route::get('/marais', [AnimalController::class, 'marais']);
Route::get('/savane', [AnimalController::class, 'savane']);

Route::middleware(['isVeterinary'])->group(function () {
    Route::get('veterinary', [VeterinaryReportController::class, 'index'])->name('veterinaryReports.index');
    Route::resource('veterinaryReports', VeterinaryReportController::class)->only(['create', 'store', 'show', 'edit', 'update', 'destroy']);

    Route::get('/nourriture', [EmployeeNourritureController::class, 'veterinaryIndex'])->name('veterinary.employee.index');
});

Route::middleware(['isEmployee'])->group(function () {
    Route::get('employee', [EmployeeNourritureController::class, 'index'])->name('employee.index');
    Route::get('employee/create', [EmployeeNourritureController::class, 'create'])->name('employee.create');
    Route::post('employee', [EmployeeNourritureController::class, 'store'])->name('employee.store');
    Route::get('employee/{id}/edit', [EmployeeNourritureController::class, 'edit'])->name('employee.edit');
    Route::put('employee/{id}', [EmployeeNourritureController::class, 'update'])->name('employee.update');
    Route::delete('employee/{id}', [EmployeeNourritureController::class, 'destroy'])->name('employee.destroy');

});

resources/views/dashboardVeterinary/createReport.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Compte Rendu - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    @include('header')
    <main>
        <div class="wrapper">
            @include('sidebarVeterinary')
            <div class="main p-3">
                <section id="notes-form">
                    <div class="card">
                        <h3 class="card-header text-center text-info mb-4">Ajouter un Compte Rendu</h3>
                        <div class="card-body px-4 text-center">
                            <form action="{{ route('veterinaryReports.store') }}" method="post">
                                @csrf
                                <label for="date">Date :</label><br>
                                <input type="text" id="date" name="date" required><br>
                                <label for="animal_id">Animal :</label><br>
                                <select class="form-select" id="animal_id" name="animal_id" required>
                                    <option value="" disabled selected>Choisissez un animal</option>
                                    @foreach($animals as $animal)
                                        <option value="{{ $animal->id }}">{{ $animal->firstname }}</option>
                                    @endforeach
                                </select>
                                <label for="detail">Comptes rendus :</label><br>
                                <textarea id="detail" name="detail" rows="4" cols="50" required></textarea><br><br>
                                <input type="submit" value="Ajouter le compte rendu">
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function() {
            $("#date").datepicker({
                dateFormat: 'dd/mm/yy'
            });
        });
    </script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
<script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardVeterinary/editReport.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un Compte Rendu - Arcadia Zoo</title>
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    @include('header')
    <main>
        <div class="wrapper">
            @include('sidebarVeterinary')
            <div class="main p-3">
                <section id="notes-form">
                    <div class="card">
                        <h3 class="card-header text-center text-info mb-4">Modifier un Compte Rendu</h3>
                        <div class="card-body px-4 text-center">
                            <form action="{{ route('veterinaryReports.update', $report->id) }}" method="post">
                                @csrf
                                @method('PUT')
                                <label for="date">Date :</label><br>
                                <input type="text" id="date" name="date" value="{{ \Carbon\Carbon::parse($report->date)->format('d/m/Y') }}" required><br>
                                <label for="animal_id">Animal :</label><br>
                                <select class="form-select" id="animal_id" name="animal_id" required>
                                    <option value="" disabled selected>Choisissez un animal</option>
                                    @foreach($animals as $animal)
                                        <option value="{{ $animal->id }}" {{ $report->animal_id == $animal->id ? 'selected' : '' }}>{{ $animal->firstname }}</option>
                                    @endforeach
                                </select>
                                <label for="detail">Comptes rendus :</label><br>
                                <textarea id="detail" name="detail" rows="4" cols="50" required>{{ $report->detail }}</textarea><br><br>
                                <input type="submit" value="Modifier le compte rendu">
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function() {
            $("#date").datepicker({
                dateFormat: 'dd/mm/yy'
            });
        });
    </script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
<script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardVeterinary/index.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des comptes rendus - Arcadia Zoo</title>
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
</head>
<body>

@include('header')

<main>
    <div class="wrapper">
        @include('sidebarVeterinary')
        <div class="main p-3">
            <section id="reports">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Gestion des comptes rendus</h3>
                    <div class="card-body px-4">
                        <div class="text-center pt-4">
                            <a href="{{ route('veterinaryReports.create') }}" class="btn btn-info mb-5">Ajouter un compte rendu</a>
                        </div>
                        <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                              <tr class="table-warning">
                                  <th class="text-center">Date</th>
                                  <th class="text-center">Animal</th>
                                  <th class="text-center">Comptes rendus</th>
                                  <th class="text-center"></th>
                                  <th class="text-center"></th>
                              </tr>
                          </thead>
                          <tbody>
                              @foreach($reports as $report)
                                  <tr>
                                      <td class="text-center">{{ \Carbon\Carbon::parse($report->date)->format('d/m/Y') }}</td>
                                      <td class="text-center">{{ $report->animal->firstname ?? 'Animal non trouvé' }}</td>
                                      <td class="text-center">{{ $report->detail }}</td>
                                      <td class="px-4 py-2 text-center">
                                          <form action="{{ route('veterinaryReports.destroy', $report->id) }}" method="post">
                                              @method('delete')
                                              @csrf
                                              <button type="submit" class="btn btn-danger">Supprimer</button>
                                          </form>
                                      </td>
                                      <td class="text-center">
                                          <a href="{{ route('veterinaryReports.edit', $report->id) }}" class="btn btn-primary">Modifier</a>
                                      </td>
                                  </tr>
                              @endforeach
                          </tbody>
                      </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
<script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardVeterinary/nourriture.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultation de la nourriture donnée aux animaux - Arcadia Zoo</title>
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>
@include('header')

<main>
    <div class="wrapper">
        @include('sidebar')
        <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Consultation de la nourriture donnée aux animaux</h3>
                    <div class="card-body px-4">
                        <form method="GET" action="{{ route('veterinary.employee.index') }}">
                            <div class="container">
                                <label>Selectionner un animal</label>
                                <select class="form-select mb-4" name="animal_id" aria-label="Default select example">
                                    <option value="">Tous les animaux</option>
                                    @foreach($animals as $animal)
                                        <option value="{{ $animal->id }}">{{ $animal->firstname }}</option>
                                    @endforeach
                                </select>

                                <label for="startDate">Date de départ</label>
                                <input id="startDate" class="mb-4 form-control" type="date" name="start_date" />

                                <label for="endDate">Date de fin</label>
                                <input id="endDate" class="mb-4 form-control" type="date" name="end_date" />

                                <div class="d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary mb-4">Filtrer</button>
                                </div>
                            </div>
                        </form>

                        <table class="table table-striped table-hover">
                            <thead>
                                <tr class="table-warning">
                                    <th>Date</th>
                                    <th>Heure</th>
                                    <th>Animal</th>
                                    <th>Nourriture</th>
                                    <th>Quantité</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($nourritures as $nourriture)
                                    <tr>
                                        <td>{{ \Carbon\Carbon::parse($nourriture->date)->format('d/m/Y') }}</td>
                                        <td>{{ $nourriture->heure }}</td>
                                        <td>{{ $nourriture->animal->firstname }}</td>
                                        <td>{{ $nourriture->detail }}</td>
                                        <td>{{ $nourriture->quantité }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
<script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/script.js') }}"></script>
</body>
</html>