routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/index', function () {
    return view('index');
});

Route::get('/', function () {
    return view('accueil');
});

Route::get('/services', function () {
    return view('services');
});

Route::get('/habitats', function () {
    return view('habitats');
});

Route::get('/avis', function () {
    return view('avis');
});

Route::get('/contact', function () {
    return view('contact');
});

Route::get('/connexion', [App\Http\Controllers\ConnexionController::class, 'formulaire']);
Route::post('/connexion', [App\Http\Controllers\ConnexionController::class, 'traitement']);


Route::get('/savane', function () {
    return view('savane');
});

Route::get('/jungle', function () {
    return view('jungle');
});

Route::get('/marais', function () {
    return view('marais');
});

Route::get('/mon-compte', [App\Http\Controllers\CompteController::class, 'accueil']);

Route::get('/deconnexion', [App\Http\Controllers\CompteController::class, 'deconnexion']);

Route::post('/logout', function () {
    auth()->logout();
    return redirect('/');
})->name('logout');


Route::middleware(['isAdmin'])->group(function () {
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal']);
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal'])->name('admin.dashboard');

    Route::get('gestionDesServices', [\App\Http\Controllers\ServiceController::class, 'indexGestionService'])->name('gestionDesServices');
    Route::resource('gestionDesServices', \App\Http\Controllers\ServiceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesHabitats', [\App\Http\Controllers\HabitatController::class, 'indexGestionHabitat'])->name('gestionDesHabitats');
    Route::resource('gestionDesHabitats', \App\Http\Controllers\HabitatController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesAnimaux', [\App\Http\Controllers\AnimalController::class, 'indexGestionAnimal'])->name('gestionDesAnimaux');
    Route::resource('gestionDesAnimaux', \App\Http\Controllers\AnimalController::class)->only(['destroy', 'show', 'edit', 'update', 'create', 'store']);

    Route::get('gestionDesRaces', [\App\Http\Controllers\RaceController::class, 'indexGestionRace'])->name('gestionDesRaces');
    Route::resource('gestionDesRaces', \App\Http\Controllers\RaceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('ajout-Compte', [\App\Http\Controllers\UserController::class, 'index'])->name('ajoutCompte');
    Route::resource('ajout-Compte', \App\Http\Controllers\UserController::class)->only(['store']);

    Route::get('/indexHoraires', function () {
        return view('indexHoraires');
    });

    Route::get('/indexComptesRendus', [App\Http\Controllers\VeterinaryReportController::class, 'adminIndex'])->name('admin.veterinaryReports.index');
});

use App\Http\Controllers\AnimalController;
use App\Http\Controllers\EmployeeNourritureController;
use App\Http\Controllers\VeterinaryReportController;
Route::get('/animal/{id}', [AnimalController::class, 'showAnimalDetails'])->name('animal.details');
Route::post('/animal/{id}/increment-view', [AnimalController::class, 'incrementView'])->name('animal.incrementView');

Route::get('/jungle', [AnimalController::class, 'jungle']);
Route::get('/marais', [AnimalController::class, 'marais']);
Route::get('/savane', [AnimalController::class, 'savane']);

Route::middleware(['isVeterinary'])->group(function () {
    Route::get('veterinary', [VeterinaryReportController::class, 'index'])->name('veterinaryReports.index');
    Route::resource('veterinaryReports', VeterinaryReportController::class)->only(['create', 'store', 'show', 'edit', 'update', 'destroy']);

    Route::get('/nourriture', [EmployeeNourritureController::class, 'veterinaryIndex'])->name('veterinary.employee.index');
});

Route::middleware(['isEmployee'])->group(function () {
    Route::get('employee', [EmployeeNourritureController::class, 'index'])->name('employee.index');
    Route::get('employee/create', [EmployeeNourritureController::class, 'create'])->name('employee.create');
    Route::post('employee', [EmployeeNourritureController::class, 'store'])->name('employee.store');
    Route::get('employee/{id}/edit', [EmployeeNourritureController::class, 'edit'])->name('employee.edit');
    Route::put('employee/{id}', [EmployeeNourritureController::class, 'update'])->name('employee.update');
    Route::delete('employee/{id}', [EmployeeNourritureController::class, 'destroy'])->name('employee.destroy');

});

resources/views/addAccount/index.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un compte - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
          @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Créer un compte</h3>
                  <div class="card-body px-4">
                    <form action="{{route('ajout-Compte.store')}}" method="POST" class="">
                      @csrf
                      @method('POST')
                      <div class="container">
                        <div class="form-group">
                          <label for="email">Adresse mail</label>
                          <input type="email" class="form-control" name="email" id="email" placeholder="test@gmail.com">
                        </div> 
                        <div class="form-group">
                          <label for="password">Mot de passe</label>
                          <input type="password" class="form-control" name="password" id="password" placeholder="25 caractères maximum">
                        </div>
                        <div class="form-group">
                            <label for="selection">Type de compte</label>
                            <select id="selection" class="form-control" name="role_id"> <!-- Ajout de l'attribut name -->
                                @foreach($roles as $role)
                                    @if(strtolower($role->label) === 'employé' || strtolower($role->label) === 'vétérinaire')
                                        <option value="{{ $role->id }}">{{ $role->label }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>

                      </fieldset>
                    </form>
                    <div class="text-center pt-4">
                      <input type="submit" value="Ajouter l'utilisateur">
                    </div>
                    </div>
                  </div>
                </div>
              </section>
          </div>
      </div>
    </main>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>