routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/index', function () {
    return view('index');
});

Route::get('/', function () {
    return view('accueil');
});

Route::get('/services', function () {
    return view('services');
});

Route::get('/habitats', function () {
    return view('habitats');
});

Route::get('/avis', function () {
    return view('avis');
});

Route::get('/contact', function () {
    return view('contact');
});

Route::get('/connexion', [App\Http\Controllers\ConnexionController::class, 'formulaire']);
Route::post('/connexion', [App\Http\Controllers\ConnexionController::class, 'traitement']);


Route::get('/savane', function () {
    return view('savane');
});

Route::get('/jungle', function () {
    return view('jungle');
});

Route::get('/marais', function () {
    return view('marais');
});

Route::get('/mon-compte', [App\Http\Controllers\CompteController::class, 'accueil']);

Route::get('/deconnexion', [App\Http\Controllers\CompteController::class, 'deconnexion']);

Route::post('/logout', function () {
    auth()->logout();
    return redirect('/');
})->name('logout');


Route::middleware(['isAdmin'])->group(function () {
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal']);
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal'])->name('admin.dashboard');

    Route::get('gestionDesServices', [\App\Http\Controllers\ServiceController::class, 'indexGestionService'])->name('gestionDesServices');
    Route::resource('gestionDesServices', \App\Http\Controllers\ServiceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesHabitats', [\App\Http\Controllers\HabitatController::class, 'indexGestionHabitat'])->name('gestionDesHabitats');
    Route::resource('gestionDesHabitats', \App\Http\Controllers\HabitatController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesAnimaux', [\App\Http\Controllers\AnimalController::class, 'indexGestionAnimal'])->name('gestionDesAnimaux');
    Route::resource('gestionDesAnimaux', \App\Http\Controllers\AnimalController::class)->only(['destroy', 'show', 'edit', 'update', 'create', 'store']);

    Route::get('gestionDesRaces', [\App\Http\Controllers\RaceController::class, 'indexGestionRace'])->name('gestionDesRaces');
    Route::resource('gestionDesRaces', \App\Http\Controllers\RaceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('ajout-Compte', [\App\Http\Controllers\UserController::class, 'index'])->name('ajoutCompte');
    Route::resource('ajout-Compte', \App\Http\Controllers\UserController::class)->only(['store']);

    Route::get('/indexHoraires', function () {
        return view('indexHoraires');
    });

    Route::get('/indexComptesRendus', [App\Http\Controllers\VeterinaryReportController::class, 'adminIndex'])->name('admin.veterinaryReports.index');
});

use App\Http\Controllers\AnimalController;
use App\Http\Controllers\EmployeeNourritureController;
use App\Http\Controllers\VeterinaryReportController;
Route::get('/animal/{id}', [AnimalController::class, 'showAnimalDetails'])->name('animal.details');
Route::post('/animal/{id}/increment-view', [AnimalController::class, 'incrementView'])->name('animal.incrementView');

Route::get('/jungle', [AnimalController::class, 'jungle']);
Route::get('/marais', [AnimalController::class, 'marais']);
Route::get('/savane', [AnimalController::class, 'savane']);

Route::middleware(['isVeterinary'])->group(function () {
    Route::get('veterinary', [VeterinaryReportController::class, 'index'])->name('veterinaryReports.index');
    Route::resource('veterinaryReports', VeterinaryReportController::class)->only(['create', 'store', 'show', 'edit', 'update', 'destroy']);

    Route::get('/nourriture', [EmployeeNourritureController::class, 'veterinaryIndex'])->name('veterinary.employee.index');
});

Route::middleware(['isEmployee'])->group(function () {
    Route::get('employee', [EmployeeNourritureController::class, 'index'])->name('employee.index');
    Route::get('employee/create', [EmployeeNourritureController::class, 'create'])->name('employee.create');
    Route::post('employee', [EmployeeNourritureController::class, 'store'])->name('employee.store');
    Route::get('employee/{id}/edit', [EmployeeNourritureController::class, 'edit'])->name('employee.edit');
    Route::put('employee/{id}', [EmployeeNourritureController::class, 'update'])->name('employee.update');
    Route::delete('employee/{id}', [EmployeeNourritureController::class, 'destroy'])->name('employee.destroy');

});

resources/views/gestion/createAnimal.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Animal - Arcadia Zoo</title>
    <link rel="stylesheet" href="../scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

<main>
    <div class="wrapper">
        @include('sidebar')
        <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Ajouter un animal</h3>
                    <div class="card-body px-4 text-center">
                    <form action="{{ route('gestionDesAnimaux.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="firstname" class="form-label">Nom de l'animal</label>
                            <input type="text" class="form-control" id="firstname" name="firstname" required>
                        </div>
                        <div class="mb-3">
                            <label for="race_id" class="form-label">Race</label>
                            <select class="form-select" id="race_id" name="race_id" required>
                                <option value="" disabled selected>Choisissez une race</option>
                                @foreach($races as $race)
                                    <option value="{{ $race->id }}">{{ $race->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="habitat_id" class="form-label">Habitat</label>
                            <select class="form-select" id="habitat_id" name="habitat_id" required>
                                <option value="" disabled selected>Choisissez un habitat</option>
                                @foreach($habitats as $habitat)
                                    <option value="{{ $habitat->id }}">{{ $habitat->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="image" class="form-label">Image de l'animal</label>
                            <input type="file" class="form-control" id="image" name="image">
                        </div>
                        <button type="submit" class="btn btn-info">Ajouter l'animal</button>
                    </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/gestion/createHabitat.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Habitat - Arcadia Zoo</title>
    <link rel="stylesheet" href="../scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

<main>
    <div class="wrapper">
        @include('sidebar')
        <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Ajouter un habitat</h3>
                    <div class="card-body px-4 text-center">
                        <form action="{{ route('gestionDesHabitats.store') }}" method="post">
                            @csrf
                            <label for="nomHabitat">Nom du habitat :</label><br>
                            <input type="text" id="nomHabitat" name="nomHabitat" required><br>
                            <label for="description">Description :</label><br>
                            <textarea id="description" name="description" rows="4" cols="50" required></textarea><br>
                            <br>
                            <input type="submit" value="Ajouter l'habitat">
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/gestion/createRace.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter une Race - Arcadia Zoo</title>
    <link rel="stylesheet" href="../scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

<main>
    <div class="wrapper">
        @include('sidebar')
        <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Ajouter une Race</h3>
                    <div class="card-body px-4 text-center">
                        <form action="{{ route('gestionDesRaces.store') }}" method="post">
                            @csrf
                            <label for="nomRace">Nom de la race :</label><br>
                            <input type="text" id="nomRace" name="nomRace" required><br>
                            <br>
                            <input type="submit" value="Ajouter la race">
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/gestion/indexAnimal.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des animaux - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
        @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Gestion des animaux</h3>
                  <div class="card-body px-4">
                  
                  <div class="text-center pt-4">
                    <a href="{{ route('gestionDesAnimaux.create') }}" class="btn btn-info mb-5">Ajouter un animal</a>
                  </div>

                    <form>
                    <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                            <tr class="table-warning">
                              <th>Nom de l'animal</th>
                              <th>Race</th>
                              <!-- <th>Image</th> -->
                              <th>Habitat</th>
                              <th></th>
                              <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($animaux as $animal)
                              <tr>
                                <td>{{$animal->firstname}}</td>
                                <td>{{$animal->race->name}}</td>
                                <!-- <td>Lien</td> -->
                                <td>{{$animal->habitat->name}}</td>
                                <td class="px-4 py-2 text-center">
                                  <form action="{{route('gestionDesAnimaux.destroy',$animal->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                  </form>
                                </td>
                                <td>
                                  <a href="{{ route('gestionDesAnimaux.show',$animal->id) }}" class="btn btn-primary">Modifier cet animal</a>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                      </fieldset>
                      </form>
                    </div>
                  </div>
                </div>
            </section>
          </div>
      </div>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/gestion/indexHabitat.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des habitats - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
        @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Gestion des habitats</h3>
                  <div class="card-body px-4">
                  
                  <div class="text-center pt-4">
                    <a href="{{ route('gestionDesHabitats.create') }}" class="btn btn-info mb-5">Ajouter un habitat</a>
                  </div>

                    <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                            <tr class="table-warning">
                              <th class="text-center">Nom de l'habitat</th>
                              <th class="text-center">Description</th>
                              <!-- <th class="text-center">Image</th> -->
                              <th class="text-center"></th>
                              <th class="text-center"></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($habitats as $habitat)
                              <tr>
                                <td>{{$habitat->name}}</td>
                                <td>{{$habitat->description}}</td>
                                <!-- <td>Lien</td> -->
                                <td class="px-4 py-2 text-center">
                                  <form action="{{route('gestionDesHabitats.destroy',$habitat->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                  </form>
                                </td>
                                <td>
                                  <a href="{{ route('gestionDesHabitats.show',$habitat->id) }}" class="btn btn-primary">Modifier cet habitat</a>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </section>
          </div>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/gestion/indexRace.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des Races - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
        @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Gestion des races</h3>
                  <div class="card-body px-4">
                  
                  <div class="text-center pt-4">
                    <a href="{{ route('gestionDesRaces.create') }}" class="btn btn-info mb-5">Ajouter une race</a>
                  </div>

                    <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                            <tr class="table-warning">
                              <th class="text-center">Nom de la race</th>
                              <th class="text-center"></th>
                              <th class="text-center"></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($races as $race)
                              <tr>
                                <td>{{$race->name}}</td>
                                <!-- <td>Lien</td> -->
                                <td class="px-4 py-2 text-center">
                                  <form action="{{route('gestionDesRaces.destroy',$race->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                  </form>
                                </td>
                                <td>
                                  <a href="{{ route('gestionDesRaces.show',$race->id) }}" class="btn btn-primary">Modifier cette race</a>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </section>
          </div>
          </div>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/gestion/indexService.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des services - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
        @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Gestion des services</h3>
                  <div class="card-body px-4">
                  
                  <div class="text-center pt-4">
                    <a href="{{ route('gestionDesServices.create') }}" class="btn btn-info mb-5">Ajouter un service</a>
                  </div>

                    <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                            <tr class="table-warning">
                              <th class="text-center">Nom du service</th>
                              <th class="text-center">Description</th>
                              <th class="text-center"></th>
                              <th class="text-center"></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($services as $service)
                              <tr>
                                <td>{{$service->name}}</td>
                                <td>{{$service->description}}</td>
                                <!-- <td>Lien</td> -->
                                <td class="px-4 py-2 text-center">
                                  <form action="{{route('gestionDesServices.destroy',$service->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                  </form>
                                </td>
                                <td>
                                  <a href="{{ route('gestionDesServices.show',$service->id) }}" class="btn btn-primary">Modifier ce service</a>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </section>
          </div>
          </div>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>