routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/index', function () {
    return view('index');
});

Route::get('/', function () {
    return view('accueil');
});

Route::get('/services', function () {
    return view('services');
});

Route::get('/habitats', function () {
    return view('habitats');
});

Route::get('/avis', function () {
    return view('avis');
});

Route::get('/contact', function () {
    return view('contact');
});

Route::get('/connexion', [App\Http\Controllers\ConnexionController::class, 'formulaire']);
Route::post('/connexion', [App\Http\Controllers\ConnexionController::class, 'traitement']);


Route::get('/savane', function () {
    return view('savane');
});

Route::get('/jungle', function () {
    return view('jungle');
});

Route::get('/marais', function () {
    return view('marais');
});

Route::get('/mon-compte', [App\Http\Controllers\CompteController::class, 'accueil']);

Route::get('/deconnexion', [App\Http\Controllers\CompteController::class, 'deconnexion']);

Route::post('/logout', function () {
    auth()->logout();
    return redirect('/');
})->name('logout');


Route::middleware(['isAdmin'])->group(function () {
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal']);
    Route::get('admin', [\App\Http\Controllers\AnimalController::class, 'indexDashboardAnimal'])->name('admin.dashboard');

    Route::get('gestionDesServices', [\App\Http\Controllers\ServiceController::class, 'indexGestionService'])->name('gestionDesServices');
    Route::resource('gestionDesServices', \App\Http\Controllers\ServiceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesHabitats', [\App\Http\Controllers\HabitatController::class, 'indexGestionHabitat'])->name('gestionDesHabitats');
    Route::resource('gestionDesHabitats', \App\Http\Controllers\HabitatController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('gestionDesAnimaux', [\App\Http\Controllers\AnimalController::class, 'indexGestionAnimal'])->name('gestionDesAnimaux');
    Route::resource('gestionDesAnimaux', \App\Http\Controllers\AnimalController::class)->only(['destroy', 'show', 'edit', 'update', 'create', 'store']);

    Route::get('gestionDesRaces', [\App\Http\Controllers\RaceController::class, 'indexGestionRace'])->name('gestionDesRaces');
    Route::resource('gestionDesRaces', \App\Http\Controllers\RaceController::class)->only(['destroy', 'show', 'update', 'create', 'store']);

    Route::get('ajout-Compte', [\App\Http\Controllers\UserController::class, 'index'])->name('ajoutCompte');
    Route::resource('ajout-Compte', \App\Http\Controllers\UserController::class)->only(['store']);

    Route::get('/indexHoraires', function () {
        return view('indexHoraires');
    });

    Route::get('/indexComptesRendus', [App\Http\Controllers\VeterinaryReportController::class, 'adminIndex'])->name('admin.veterinaryReports.index');
});

use App\Http\Controllers\AnimalController;
use App\Http\Controllers\EmployeeNourritureController;
use App\Http\Controllers\VeterinaryReportController;
Route::get('/animal/{id}', [AnimalController::class, 'showAnimalDetails'])->name('animal.details');
Route::post('/animal/{id}/increment-view', [AnimalController::class, 'incrementView'])->name('animal.incrementView');

Route::get('/jungle', [AnimalController::class, 'jungle']);
Route::get('/marais', [AnimalController::class, 'marais']);
Route::get('/savane', [AnimalController::class, 'savane']);

Route::middleware(['isVeterinary'])->group(function () {
    Route::get('veterinary', [VeterinaryReportController::class, 'index'])->name('veterinaryReports.index');
    Route::resource('veterinaryReports', VeterinaryReportController::class)->only(['create', 'store', 'show', 'edit', 'update', 'destroy']);

    Route::get('/nourriture', [EmployeeNourritureController::class, 'veterinaryIndex'])->name('veterinary.employee.index');
});

Route::middleware(['isEmployee'])->group(function () {
    Route::get('employee', [EmployeeNourritureController::class, 'index'])->name('employee.index');
    Route::get('employee/create', [EmployeeNourritureController::class, 'create'])->name('employee.create');
    Route::post('employee', [EmployeeNourritureController::class, 'store'])->name('employee.store');
    Route::get('employee/{id}/edit', [EmployeeNourritureController::class, 'edit'])->name('employee.edit');
    Route::put('employee/{id}', [EmployeeNourritureController::class, 'update'])->name('employee.update');
    Route::delete('employee/{id}', [EmployeeNourritureController::class, 'destroy'])->name('employee.destroy');

});

resources/views/dashboardEmployee/createNourriture.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter de la nourriture donnée - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    @include('header')
    <main>
        <div class="wrapper">
            @include('sidebarEmployee')
            <div class="main p-3">
                <section id="notes-form">
                    <div class="card">
                        <h3 class="card-header text-center text-info mb-4">Ajouter la nourriture donnée</h3>
                        <div class="card-body px-4 text-center">
                        <form action="{{ route('employee.store') }}" method="post">
                            @csrf
                            <label for="date">Date :</label><br>
                            <input type="text" id="date" name="date" required><br>
                            <div class="form-group">
                                <label for="heure">Heure</label>
                                <input type="time" class="form-control" id="heure" name="heure" required>
                            </div>
                            <label for="animal_id">Animal :</label><br>
                            <select class="form-select" id="animal_id" name="animal_id" required>
                                <option value="" disabled selected>Choisissez un animal</option>
                                @foreach($animals as $animal)
                                    <option value="{{ $animal->id }}">{{ $animal->firstname }}</option>
                                @endforeach
                            </select>
                            <label for="detail">Nourriture donnée :</label><br>
                            <textarea id="detail" name="detail" rows="4" cols="50" required></textarea><br><br>
                            <label for="quantité">Quantité :</label><br>
                            <input type="text" id="quantité" name="quantité" required><br><br>
                            <input type="submit" value="Ajouter la nourriture donnée">
                        </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function() {
            $("#date").datepicker({
                dateFormat: 'dd/mm/yy'
            });
        });
    </script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
<script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardEmployee/createService.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un Service - Arcadia Zoo</title>
    <link rel="stylesheet" href="../scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

<main>
    <div class="wrapper">
        @include('sidebar')
        <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Ajouter un Service</h3>
                    <div class="card-body px-4 text-center">
                        <form action="{{ route('gestionDesServices.store') }}" method="post">
                            @csrf
                            <label for="nomService">Nom du service :</label><br>
                            <input type="text" id="nomService" name="nomService" required><br>
                            <label for="description">Description :</label><br>
                            <textarea id="description" name="description" rows="4" cols="50" required></textarea><br>
                            <br>
                            <input type="submit" value="Ajouter le service">
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardEmployee/editNourriture.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier la nourriture donnée - Arcadia Zoo</title>
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
    <body>
        @include('header')
        <main>
            <div class="wrapper">
                @include('sidebarEmployee')
                <div class="main p-3">
                    <section id="notes-form">
                        <div class="card">
                            <h3 class="card-header text-center text-info mb-4">Modifier la nourriture donnée</h3>
                            <div class="card-body px-4 text-center">
                                <form action="{{ route('employee.update', $nourriture->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <label for="date">Date :</label><br>
                                    <input type="text" id="date" name="date" value="{{ \Carbon\Carbon::parse($nourriture->date)->format('d/m/Y') }}" required><br>
                                    <div class="form-group">
                                        <label for="heure">Heure</label>
                                        <input type="time" class="form-control" id="heure" name="heure" value="{{ $nourriture->heure }}" required>
                                    </div>
                                    <label for="animal_id">Animal :</label><br>
                                    <select class="form-select" id="animal_id" name="animal_id" required>
                                        <option value="" disabled>Choisissez un animal</option>
                                        @foreach($animals as $animal)
                                            <option value="{{ $animal->id }}" {{ $nourriture->animal_id == $animal->id ? 'selected' : '' }}>{{ $animal->firstname }}</option>
                                        @endforeach
                                    </select>
                                    <label for="detail">Nourriture donnée :</label><br>
                                    <textarea id="detail" name="detail" rows="4" cols="50" required>{{ $nourriture->detail }}</textarea><br><br>
                                    <label for="quantité">Quantité :</label><br>
                                    <textarea id="quantité" name="quantité" rows="4" cols="50" required>{{ $nourriture->quantité }}</textarea><br><br>
                                    <input type="submit" value="Modifier la nourriture donnée">
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </main>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
            $(document).ready(function() {
                $("#date").datepicker({
                    dateFormat: 'dd/mm/yy'
                });
            });
        </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/script.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{{ asset('js/script.js') }}"></script>
    </body>
</html>

resources/views/dashboardEmployee/index.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de la nourriture donnée aux animaux - Arcadia Zoo</title>
    <link rel="stylesheet" href="{{ asset('scss/main.css') }}">
</head>
<body>

@include('header')

<main>
    <div class="wrapper">
        @include('sidebarEmployee')
        <div class="main p-3">
            <section id="nourritures">
                <div class="card">
                    <h3 class="card-header text-center text-info mb-4">Gestion de la nourriture donnée aux animaux</h3>
                    <div class="card-body px-4">
                        <div class="text-center pt-4">
                            <a href="{{ route('employee.create') }}" class="btn btn-info mb-5">Ajouter la nourriture donnée</a>
                        </div>
                        <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                              <tr class="table-warning">
                                  <th class="text-center">Date</th>
                                  <th class="text-center">Heure</th>
                                  <th class="text-center">Animal</th>
                                  <th class="text-center">Nourriture</th>
                                  <th class="text-center">Quantité</th>
                                  <th class="text-center"></th>
                                  <th class="text-center"></th>
                              </tr>
                          </thead>
                            <tbody>
                            @foreach($nourritures as $nourriture)
                                <tr>
                                    <td class="text-center">{{ \Carbon\Carbon::parse($nourriture->date)->format('d/m/Y') }}</td>
                                    <td class="text-center">{{ \Carbon\Carbon::parse($nourriture->heure)->format('H:i') }}</td>
                                    <td class="text-center">{{ $nourriture->animal->firstname ?? 'Animal non trouvé' }}</td>
                                    <td class="text-center">{{ $nourriture->detail }}</td>
                                    <td class="text-center">{{ $nourriture->quantité }}</td>
                                    <td class="px-4 py-2 text-center">
                                        <form action="{{ route('employee.destroy', $nourriture->id) }}" method="post">
                                            @method('delete')
                                            @csrf
                                            <button type="submit" class="btn btn-danger">Supprimer</button>
                                        </form>
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('employee.edit', $nourriture->id) }}" class="btn btn-primary">Modifier</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                      </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
<script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardEmployee/indexService.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des services - Arcadia Zoo</title>
    <link rel="stylesheet" href="scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
        @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Gestion des services</h3>
                  <div class="card-body px-4">
                  
                  <div class="text-center pt-4">
                    <a href="{{ route('gestionDesServices.create') }}" class="btn btn-info mb-5">Ajouter un service</a>
                  </div>

                    <div class="container">
                        <table class="table table-striped table-hover">
                          <thead>
                            <tr class="table-warning">
                              <th class="text-center">Nom du service</th>
                              <th class="text-center">Description</th>
                              <th class="text-center"></th>
                              <th class="text-center"></th>
                            </tr>
                          </thead>
                          <tbody>
                            @foreach($services as $service)
                              <tr>
                                <td>{{$service->name}}</td>
                                <td>{{$service->description}}</td>
                                <!-- <td>Lien</td> -->
                                <td class="px-4 py-2 text-center">
                                  <form action="{{route('gestionDesServices.destroy',$service->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Supprimer</button>
                                  </form>
                                </td>
                                <td>
                                  <a href="{{ route('gestionDesServices.show',$service->id) }}" class="btn btn-primary">Modifier ce service</a>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </section>
          </div>
          </div>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>

resources/views/dashboardEmployee/showService.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un service - Arcadia Zoo</title>
    <link rel="stylesheet" href="../scss/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jolly+Lodger&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital@0;1&display=swap" rel="stylesheet">
</head>
<body>

@include('header')

    <main>
      <div class="wrapper">
        @include('sidebar')
          <div class="main p-3">
            <section id="notes-form">
                <div class="card">
                  <h3 class="card-header text-center text-info mb-4">Gestion des services</h3>
                  <div class="card-body px-4 text-center">
                    <form action="{{ route('gestionDesServices.update', $service->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <label for="nomService">Nom du service :</label><br>
                        <input type="text" id="nomService" name="nomService" value="{{ $service->name }}"><br>
                        <label for="description">Description :</label><br>
                        <textarea id="description" name="description" rows="4" cols="50">{{ $service->description }}</textarea><br>
                        <br>
                        <input type="submit" value="Modifier le service">
                    </form>
                  </div>
                </div>
            </section>
          </div>
      </div>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"></script>
  <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="js/script.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('js/script.js') }}"></script>
</body>
</html>